#!/bin/bash
BASE_DIR=${HOME}/Develops/Emacs/packages/elegant-emacs
exec emacs -q \
   -L "${BASE_DIR}" \
   -L "${BASE_DIR}/packages/evil" \
   -L "${BASE_DIR}/packages/which-key"  \
   -L "${BASE_DIR}/packages/aggressive-indent-mode"  \
   -l sanity.el -l elegance.el -l init.el \
   "$@"
