#!/bin/bash
BASE_DIR=${HOME}/Develops/fEmacs
exec emacs -q \
   -L "${BASE_DIR}" \
   -L "${BASE_DIR}/packages/evil" \
   -L "${BASE_DIR}/packages/which-key"  \
   -L "${BASE_DIR}/packages/general"  \
   -L "${BASE_DIR}/packages/aggressive-indent-mode"  \
   -L "${BASE_DIR}/packages/powerline"  \
   -L "${BASE_DIR}/packages/centaur-tabs"  \
   -L "${BASE_DIR}/packages/ranger"  \
   -L "${BASE_DIR}/packages/fzf"  \
   -L "${BASE_DIR}/packages/transient/lisp"  \
   -L "${BASE_DIR}/packages/wgrep"  \
   -L "${BASE_DIR}/packages/s"  \
   -L "${BASE_DIR}/packages/rg"  \
   -L "${BASE_DIR}/packages/js2-mode"  \
   -L "${BASE_DIR}/packages/dash"  \
   -L "${BASE_DIR}/packages/with-editor"  \
   -L "${BASE_DIR}/packages/magit/lisp"  \
   -L "${BASE_DIR}/packages/flycheck"  \
   -L "${BASE_DIR}/packages/rainbow-delimiters"  \
   -l "${BASE_DIR}/sanity.el" \
   -l "${BASE_DIR}/elegance.el" \
   -l "${BASE_DIR}/init.el" \
   -l "${BASE_DIR}/colorize-identifiers.el" \
   "$@"
